// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.7.1
// source: packet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Id1 int32

const (
	Id1_LOGIN      Id1 = 0 //登陆管理
	Id1_KEEPALIVE  Id1 = 1 //状态更新
	Id1_UPDATE     Id1 = 2 //更新课程状态
	Id1_FILE       Id1 = 3 //文件下载
	Id1_FILEUPLOAD Id1 = 4 //文件上传
	Id1_LESSONS    Id1 = 5 //课程清单
	Id1_DEBUG      Id1 = 9 //待使用
)

// Enum value maps for Id1.
var (
	Id1_name = map[int32]string{
		0: "LOGIN",
		1: "KEEPALIVE",
		2: "UPDATE",
		3: "FILE",
		4: "FILEUPLOAD",
		5: "LESSONS",
		9: "DEBUG",
	}
	Id1_value = map[string]int32{
		"LOGIN":      0,
		"KEEPALIVE":  1,
		"UPDATE":     2,
		"FILE":       3,
		"FILEUPLOAD": 4,
		"LESSONS":    5,
		"DEBUG":      9,
	}
)

func (x Id1) Enum() *Id1 {
	p := new(Id1)
	*p = x
	return p
}

func (x Id1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Id1) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_proto_enumTypes[0].Descriptor()
}

func (Id1) Type() protoreflect.EnumType {
	return &file_packet_proto_enumTypes[0]
}

func (x Id1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Id1.Descriptor instead.
func (Id1) EnumDescriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{0}
}

type Gesture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roll        float32 `protobuf:"fixed32,1,opt,name=roll,proto3" json:"roll,omitempty"`
	Pitch       float32 `protobuf:"fixed32,2,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Yaw         float32 `protobuf:"fixed32,3,opt,name=yaw,proto3" json:"yaw,omitempty"`
	MinEar      float32 `protobuf:"fixed32,4,opt,name=min_ear,json=minEar,proto3" json:"min_ear,omitempty"`
	Mar         float32 `protobuf:"fixed32,5,opt,name=mar,proto3" json:"mar,omitempty"`
	Mdst        float32 `protobuf:"fixed32,6,opt,name=mdst,proto3" json:"mdst,omitempty"`
	LFronterArm float32 `protobuf:"fixed32,7,opt,name=LFronterArm,proto3" json:"LFronterArm,omitempty"`
	LUpperArm   float32 `protobuf:"fixed32,8,opt,name=LUpperArm,proto3" json:"LUpperArm,omitempty"`
	RFronterArm float32 `protobuf:"fixed32,9,opt,name=RFronterArm,proto3" json:"RFronterArm,omitempty"`
	RUpperArm   float32 `protobuf:"fixed32,10,opt,name=RUpperArm,proto3" json:"RUpperArm,omitempty"`
}

func (x *Gesture) Reset() {
	*x = Gesture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gesture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gesture) ProtoMessage() {}

func (x *Gesture) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gesture.ProtoReflect.Descriptor instead.
func (*Gesture) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Gesture) GetRoll() float32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

func (x *Gesture) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *Gesture) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *Gesture) GetMinEar() float32 {
	if x != nil {
		return x.MinEar
	}
	return 0
}

func (x *Gesture) GetMar() float32 {
	if x != nil {
		return x.Mar
	}
	return 0
}

func (x *Gesture) GetMdst() float32 {
	if x != nil {
		return x.Mdst
	}
	return 0
}

func (x *Gesture) GetLFronterArm() float32 {
	if x != nil {
		return x.LFronterArm
	}
	return 0
}

func (x *Gesture) GetLUpperArm() float32 {
	if x != nil {
		return x.LUpperArm
	}
	return 0
}

func (x *Gesture) GetRFronterArm() float32 {
	if x != nil {
		return x.RFronterArm
	}
	return 0
}

func (x *Gesture) GetRUpperArm() float32 {
	if x != nil {
		return x.RUpperArm
	}
	return 0
}

type Simpgest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Present bool `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	Handsup bool `protobuf:"varint,2,opt,name=handsup,proto3" json:"handsup,omitempty"`
}

func (x *Simpgest) Reset() {
	*x = Simpgest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Simpgest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Simpgest) ProtoMessage() {}

func (x *Simpgest) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Simpgest.ProtoReflect.Descriptor instead.
func (*Simpgest) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{1}
}

func (x *Simpgest) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *Simpgest) GetHandsup() bool {
	if x != nil {
		return x.Handsup
	}
	return false
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id1      Id1       `protobuf:"varint,1,opt,name=id1,proto3,enum=pb.Id1" json:"id1,omitempty"`
	Id2      uint32    `protobuf:"varint,2,opt,name=id2,proto3" json:"id2,omitempty"`
	SorTid   string    `protobuf:"bytes,3,opt,name=SorTid,proto3" json:"SorTid,omitempty"`
	Gesture  *Gesture  `protobuf:"bytes,4,opt,name=gesture,proto3" json:"gesture,omitempty"`
	Simpgest *Simpgest `protobuf:"bytes,5,opt,name=simpgest,proto3" json:"simpgest,omitempty"`
	Filedata []byte    `protobuf:"bytes,6,opt,name=filedata,proto3" json:"filedata,omitempty"`
	Mesg     string    `protobuf:"bytes,7,opt,name=mesg,proto3" json:"mesg,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{2}
}

func (x *Packet) GetId1() Id1 {
	if x != nil {
		return x.Id1
	}
	return Id1_LOGIN
}

func (x *Packet) GetId2() uint32 {
	if x != nil {
		return x.Id2
	}
	return 0
}

func (x *Packet) GetSorTid() string {
	if x != nil {
		return x.SorTid
	}
	return ""
}

func (x *Packet) GetGesture() *Gesture {
	if x != nil {
		return x.Gesture
	}
	return nil
}

func (x *Packet) GetSimpgest() *Simpgest {
	if x != nil {
		return x.Simpgest
	}
	return nil
}

func (x *Packet) GetFiledata() []byte {
	if x != nil {
		return x.Filedata
	}
	return nil
}

func (x *Packet) GetMesg() string {
	if x != nil {
		return x.Mesg
	}
	return ""
}

var File_packet_proto protoreflect.FileDescriptor

var file_packet_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x84, 0x02, 0x0a, 0x07, 0x47, 0x65, 0x73, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x72, 0x6f,
	0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x70, 0x69, 0x74, 0x63, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x79, 0x61, 0x77, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x79, 0x61, 0x77, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x69,
	0x6e, 0x5f, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x6d, 0x69, 0x6e,
	0x45, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x03, 0x6d, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x64, 0x73, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x04, 0x6d, 0x64, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x46, 0x72,
	0x6f, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b,
	0x4c, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x4c,
	0x55, 0x70, 0x70, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09,
	0x4c, 0x55, 0x70, 0x70, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x46, 0x72,
	0x6f, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b,
	0x52, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x52,
	0x55, 0x70, 0x70, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09,
	0x52, 0x55, 0x70, 0x70, 0x65, 0x72, 0x41, 0x72, 0x6d, 0x22, 0x3e, 0x0a, 0x08, 0x53, 0x69, 0x6d,
	0x70, 0x67, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x75, 0x70, 0x22, 0xce, 0x01, 0x0a, 0x06, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x03, 0x69, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x64, 0x31, 0x52, 0x03, 0x69, 0x64, 0x31, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x69, 0x64,
	0x32, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x72, 0x54, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x53, 0x6f, 0x72, 0x54, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x07, 0x67, 0x65, 0x73,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x73, 0x74, 0x75, 0x72, 0x65, 0x52, 0x07, 0x67, 0x65, 0x73, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x28, 0x0a, 0x08, 0x73, 0x69, 0x6d, 0x70, 0x67, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x67, 0x65, 0x73, 0x74,
	0x52, 0x08, 0x73, 0x69, 0x6d, 0x70, 0x67, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x73, 0x67, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x73, 0x67, 0x2a, 0x5d, 0x0a, 0x03, 0x49, 0x64,
	0x31, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x4b, 0x45, 0x45, 0x50, 0x41, 0x4c, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55,
	0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45, 0x10,
	0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x49, 0x4c, 0x45, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x10,
	0x04, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x45, 0x53, 0x53, 0x4f, 0x4e, 0x53, 0x10, 0x05, 0x12, 0x09,
	0x0a, 0x05, 0x44, 0x45, 0x42, 0x55, 0x47, 0x10, 0x09, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packet_proto_rawDescOnce sync.Once
	file_packet_proto_rawDescData = file_packet_proto_rawDesc
)

func file_packet_proto_rawDescGZIP() []byte {
	file_packet_proto_rawDescOnce.Do(func() {
		file_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_packet_proto_rawDescData)
	})
	return file_packet_proto_rawDescData
}

var file_packet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_packet_proto_goTypes = []interface{}{
	(Id1)(0),         // 0: pb.Id1
	(*Gesture)(nil),  // 1: pb.Gesture
	(*Simpgest)(nil), // 2: pb.Simpgest
	(*Packet)(nil),   // 3: pb.Packet
}
var file_packet_proto_depIdxs = []int32{
	0, // 0: pb.Packet.id1:type_name -> pb.Id1
	1, // 1: pb.Packet.gesture:type_name -> pb.Gesture
	2, // 2: pb.Packet.simpgest:type_name -> pb.Simpgest
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_packet_proto_init() }
func file_packet_proto_init() {
	if File_packet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gesture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Simpgest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packet_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_proto_goTypes,
		DependencyIndexes: file_packet_proto_depIdxs,
		EnumInfos:         file_packet_proto_enumTypes,
		MessageInfos:      file_packet_proto_msgTypes,
	}.Build()
	File_packet_proto = out.File
	file_packet_proto_rawDesc = nil
	file_packet_proto_goTypes = nil
	file_packet_proto_depIdxs = nil
}
