# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packet.proto',
  package='pb',
  syntax='proto3',
  serialized_options=_b('Z\005../pb'),
  serialized_pb=_b('\n\x0cpacket.proto\x12\x02pb\"\xaf\x01\n\x07Gesture\x12\x0c\n\x04roll\x18\x01 \x01(\x02\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\x12\x0f\n\x07min_ear\x18\x04 \x01(\x02\x12\x0b\n\x03mar\x18\x05 \x01(\x02\x12\x0c\n\x04mdst\x18\x06 \x01(\x02\x12\x13\n\x0bLFronterArm\x18\x07 \x01(\x02\x12\x11\n\tLUpperArm\x18\x08 \x01(\x02\x12\x13\n\x0bRFronterArm\x18\t \x01(\x02\x12\x11\n\tRUpperArm\x18\n \x01(\x02\",\n\x08Simpgest\x12\x0f\n\x07present\x18\x01 \x01(\x08\x12\x0f\n\x07handsup\x18\x02 \x01(\x08\"\x99\x01\n\x06Packet\x12\x14\n\x03id1\x18\x01 \x01(\x0e\x32\x07.pb.Id1\x12\x0b\n\x03id2\x18\x02 \x01(\r\x12\x0e\n\x06SorTid\x18\x03 \x01(\t\x12\x1c\n\x07gesture\x18\x04 \x01(\x0b\x32\x0b.pb.Gesture\x12\x1e\n\x08simpgest\x18\x05 \x01(\x0b\x32\x0c.pb.Simpgest\x12\x10\n\x08\x66iledata\x18\x06 \x01(\x0c\x12\x0c\n\x04mesg\x18\x07 \x01(\t*]\n\x03Id1\x12\t\n\x05LOGIN\x10\x00\x12\r\n\tKEEPALIVE\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\x08\n\x04\x46ILE\x10\x03\x12\x0e\n\nFILEUPLOAD\x10\x04\x12\x0b\n\x07LESSONS\x10\x05\x12\t\n\x05\x44\x45\x42UG\x10\tB\x07Z\x05../pbb\x06proto3')
)

_ID1 = _descriptor.EnumDescriptor(
  name='Id1',
  full_name='pb.Id1',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOGIN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KEEPALIVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILEUPLOAD', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LESSONS', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=6, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=400,
  serialized_end=493,
)
_sym_db.RegisterEnumDescriptor(_ID1)

Id1 = enum_type_wrapper.EnumTypeWrapper(_ID1)
LOGIN = 0
KEEPALIVE = 1
UPDATE = 2
FILE = 3
FILEUPLOAD = 4
LESSONS = 5
DEBUG = 9



_GESTURE = _descriptor.Descriptor(
  name='Gesture',
  full_name='pb.Gesture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll', full_name='pb.Gesture.roll', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='pb.Gesture.pitch', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='pb.Gesture.yaw', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_ear', full_name='pb.Gesture.min_ear', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mar', full_name='pb.Gesture.mar', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mdst', full_name='pb.Gesture.mdst', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LFronterArm', full_name='pb.Gesture.LFronterArm', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LUpperArm', full_name='pb.Gesture.LUpperArm', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RFronterArm', full_name='pb.Gesture.RFronterArm', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RUpperArm', full_name='pb.Gesture.RUpperArm', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=196,
)


_SIMPGEST = _descriptor.Descriptor(
  name='Simpgest',
  full_name='pb.Simpgest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='present', full_name='pb.Simpgest.present', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='handsup', full_name='pb.Simpgest.handsup', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=242,
)


_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='pb.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id1', full_name='pb.Packet.id1', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id2', full_name='pb.Packet.id2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SorTid', full_name='pb.Packet.SorTid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gesture', full_name='pb.Packet.gesture', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='simpgest', full_name='pb.Packet.simpgest', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filedata', full_name='pb.Packet.filedata', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mesg', full_name='pb.Packet.mesg', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=398,
)

_PACKET.fields_by_name['id1'].enum_type = _ID1
_PACKET.fields_by_name['gesture'].message_type = _GESTURE
_PACKET.fields_by_name['simpgest'].message_type = _SIMPGEST
DESCRIPTOR.message_types_by_name['Gesture'] = _GESTURE
DESCRIPTOR.message_types_by_name['Simpgest'] = _SIMPGEST
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
DESCRIPTOR.enum_types_by_name['Id1'] = _ID1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Gesture = _reflection.GeneratedProtocolMessageType('Gesture', (_message.Message,), dict(
  DESCRIPTOR = _GESTURE,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:pb.Gesture)
  ))
_sym_db.RegisterMessage(Gesture)

Simpgest = _reflection.GeneratedProtocolMessageType('Simpgest', (_message.Message,), dict(
  DESCRIPTOR = _SIMPGEST,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:pb.Simpgest)
  ))
_sym_db.RegisterMessage(Simpgest)

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), dict(
  DESCRIPTOR = _PACKET,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:pb.Packet)
  ))
_sym_db.RegisterMessage(Packet)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
